(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SignalDesk=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const repos=['gitroomhq/postiz-app','TryGhost/Ghost','n8n-io/n8n'];
const text=(x,n=500)=>String(x??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').trim().slice(0,n);
function normalize(repo,meta,release,checkedAt){if(!repos.includes(repo))throw Error('This source is outside the public watchlist.');if(!meta||typeof meta.full_name!=='string'||meta.full_name.toLowerCase()!==repo.toLowerCase()||meta.private!==false)throw Error('Expected public repository metadata.');if(!Number.isSafeInteger(meta.stargazers_count)||meta.stargazers_count<0)throw Error('Repository star count is missing or invalid.');return {repo,description:text(meta.description),stars:meta.stargazers_count,pushedAt:date(meta.pushed_at),releaseTag:release?text(release.tag_name,100):'No public release',releaseDate:release?date(release.published_at):'',license:text(meta.license?.spdx_id||'Not specified',100),checkedAt:date(checkedAt),url:'https://github.com/'+repo};}
function date(value){if(!value)return '';const d=new Date(value);if(!Number.isFinite(d.getTime()))throw Error('A source date is invalid.');return d.toISOString();}
function changes(previous,current){if(!previous)return ['Baseline captured; no prior comparison.'];const result=[];for(const [key,label]of [['releaseTag','Latest release'],['pushedAt','Latest push'],['license','License metadata']])if(previous[key]!==current[key])result.push(label+': '+(previous[key]||'unknown')+' → '+(current[key]||'unknown'));return result.length?result:['No tracked change since the prior snapshot.'];}
function restore(data){if(!data||data.version!==1||!Array.isArray(data.records)||data.records.length!==3)throw Error('Choose a version 1 Signal Desk snapshot with three sources.');const seen=new Set();return data.records.map(r=>{if(!r||!repos.includes(r.repo)||seen.has(r.repo))throw Error('Snapshot sources must match the public watchlist.');seen.add(r.repo);if(!Number.isSafeInteger(r.stars)||r.stars<0)throw Error('Snapshot star count is missing or invalid.');return {repo:r.repo,description:text(r.description),stars:r.stars,pushedAt:date(r.pushedAt),releaseTag:text(r.releaseTag,100),releaseDate:date(r.releaseDate),license:text(r.license,100),checkedAt:date(r.checkedAt),url:'https://github.com/'+r.repo,note:text(r.note,1000),reviewed:false,changes:['Imported snapshot; refresh the public sources to verify.']};});}
function brief(records,mode){const esc=s=>text(s,3000).replace(/([\\`*_{}\[\]<>#|])/g,'\\$1');return '# Signal Desk / publishing tools\n\nSource mode: '+mode+'\n\nThese are observed repository facts and human notes, not product recommendations, sales rankings, or ROI claims. Stars describe popularity. A push is not a release.\n\n'+records.map(r=>'## '+r.repo+'\n\nStatus: '+(r.reviewed?'Human reviewed':'Draft')+'\n\nSource: '+r.url+'\n\nChecked: '+r.checkedAt+'\n\nLatest release: '+esc(r.releaseTag)+'\n\nLatest push: '+r.pushedAt+'\n\nChanges: '+r.changes.map(esc).join('; ')+'\n\nWhy it matters: '+(esc(r.note)||'Awaiting a human note.')+'\n').join('\n');}
const sample=repos.map((repo,i)=>({repo,description:['A social publishing workflow','An independent publishing platform','A workflow automation tool'][i]+' — fictional demonstration snapshot',stars:[120,240,360][i],pushedAt:'2026-10-01T12:00:00.000Z',releaseTag:'DEMO-'+(i+1),releaseDate:'2026-10-01T12:00:00.000Z',license:'Fictional fixture',checkedAt:'2026-10-09T12:00:00.000Z',url:'https://example.com/',note:'',reviewed:false,changes:['Fictional example; these values are not facts about the named repository.']}));
return {repos,normalize,changes,restore,brief,sample};
});
